country='英国'
currencyName='英镑'
symbol='£'
iso_code='GBP'
country_description='大不列颠及北爱尔兰联合王国（英语：United Kingdom of Great Britain and Northern Ireland），简称联合王国（英语：United Kingdom，缩写作UK）或不列颠（英语：Britain），中文通称「英国」。'